version = 1

[theme]
style = "industrial"
accent = "#c2410c"

[layout]
navigation = "sidebar-left"
header = true
header_title = "P1 HMI"

[write]
enabled = false
allow = []

[[alarm]]
bind = "P1.SpeedRaw"
high = 3600
low = 0
deadband = 72
inferred = true
label = "Speed RAW"

[[alarm]]
bind = "P1.SpeedSet"
high = 3600
low = 0
deadband = 72
inferred = true
label = "Speed SET"
