title = "Overview"
icon = "activity"
order = 0

[[section]]
title = "Details"
span = 12
tier = "detail"

[[section.widget]]
type = "value"
bind = "P1.Count"
inferred_interface = true
label = "Count"
span = 3
min = 0
max = 100

[[section.widget]]
type = "indicator"
bind = "global.InSignal"
label = "IN Signal"
span = 3

[[section.widget]]
type = "indicator"
bind = "global.OutSignal"
label = "OUT Signal"
span = 3
